### ISSUE TITLE
Chapter 4

### ISSUE THREAD

**Issue by RobertMara** [awscsa/awscsa.github.io#6]
**Please describe the error you're reporting**
It appears a network translation example is incorrect.

The example describes an EC2 instance with private IP address 172.31.7.10 associated with EIP 35.168.241.48.  When the instance attempts to send a packet to Internet host 198.51.100.11, it will send the following packet to the Internet gateway:

Source IP address: 172.31.7.10
Destination IP address:  35.168.241.48

I believe the Destination IP address is incorrect. I think it should be 198.51.100.11.

**Please indicate the chapter or appendix, section, and page number where the error appears (if applicable)**
Chapter 4, section "Network Address Translation", page 110

**Please include any other comments or questions**

**Comment by benpiper** [comment]
Thank you. This will be fixed in a subsequent edition.
